"""Offline licenses (lumi/license.py) and the signing script (scripts/sign_license.py).

Every key here is generated by the test. Machine locations are redirected to
a temporary folder; the registry and configuration profiles aren't read.
"""

from __future__ import annotations

import base64
import importlib.util
import json
import os
import stat
from pathlib import Path

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from lumi import license as lumi_license
from lumi import policy
from lumi.license import LicenseError

ROOT = Path(__file__).resolve().parent.parent


def _public(key: Ed25519PrivateKey) -> str:
    return base64.b64encode(key.public_key().public_bytes(serialization.Encoding.Raw,
                                                         serialization.PublicFormat.Raw)).decode()


def _signed(key: Ed25519PrivateKey, key_id: str = "luminary-test", **changes) -> dict:
    document = {"schema": lumi_license.SCHEMA, "license_id": "acme-001", "organization": "Acme", "seats": 50,
                "offline": True, "issued_at": "2026-09-27T00:00:00Z", "expires_at": "2099-01-01T00:00:00Z",
                **changes}
    signature = base64.b64encode(key.sign(lumi_license.canonical(document))).decode()
    return {"license": document, "key_id": key_id, "signature": signature}


@pytest.fixture
def machine(tmp_path, monkeypatch):
    """A machine folder standing in for %ProgramData%\\Lumi (writable only by administrators there)."""
    folder = tmp_path / "machine"
    folder.mkdir()
    monkeypatch.setattr(policy, "machine_policy_file", lambda: folder / "policy.json")
    monkeypatch.setattr(lumi_license, "_managed_key_texts", lambda: [])
    monkeypatch.delenv("LUMI_LICENSE_FILE", raising=False)
    lumi_license.reset_for_tests()
    return folder


@pytest.fixture
def key(machine):
    """Luminary's signing key, trusted through license-keys.json beside the machine policy."""
    signing = Ed25519PrivateKey.generate()
    (machine / "license-keys.json").write_text(json.dumps({"luminary-test": _public(signing)}), encoding="utf-8")
    return signing


def _write(path: Path, data: dict) -> Path:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path


class TestVerification:
    def test_a_signed_license_from_the_machine_folder(self, machine, key):
        _write(machine / "license.json", _signed(key))
        info = lumi_license.status()
        assert info["valid"] and info["organization"] == "Acme" and info["seats"] == 50
        assert info["offline_use"] == "licensed" and info["source"] == str(machine / "license.json")
        assert lumi_license.describe(info) == ("Licensed to Acme, 50 seats, valid until 2099-01-01T00:00:00Z. "
                                               "Offline use is licensed.")

    def test_built_in_keys_are_trusted_and_win(self, machine, monkeypatch):
        luminary = Ed25519PrivateKey.generate()
        monkeypatch.setattr(lumi_license, "BUILTIN_KEYS", {"luminary-test": _public(luminary)})
        # An administrator's key under the same id doesn't replace Luminary's.
        (machine / "license-keys.json").write_text(json.dumps(
            {"luminary-test": _public(Ed25519PrivateKey.generate())}), encoding="utf-8")
        _write(machine / "license.json", _signed(luminary))
        assert lumi_license.status()["valid"]

    def test_tampered_or_untrusted_licenses_are_refused(self, machine, key):
        document = _signed(key)
        document["license"]["seats"] = 5000
        _write(machine / "license.json", document)
        info = lumi_license.status()
        assert not info["valid"] and "signature doesn't match" in info["error"]
        assert info["offline_use"] == "unlicensed"
        lumi_license.reset_for_tests()
        _write(machine / "license.json", _signed(Ed25519PrivateKey.generate(), key_id="someone-else"))
        assert "doesn't trust" in lumi_license.status()["error"]

    def test_keys_from_user_writable_places_are_never_trusted(self, machine, tmp_path, monkeypatch):
        from lumi.paths import state_home

        signing = Ed25519PrivateKey.generate()
        entry = json.dumps({"luminary-test": _public(signing)})
        state_home().mkdir(parents=True, exist_ok=True)
        (state_home() / "license-keys.json").write_text(entry, encoding="utf-8")
        (state_home() / "policy-keys.json").write_text(entry, encoding="utf-8")
        monkeypatch.setenv("LUMI_LICENSE_KEYS", entry)
        _write(state_home() / "license.json", _signed(signing))
        info = lumi_license.status()
        assert not info["valid"] and "doesn't trust" in info["error"]

    def test_expiry_and_offline_use(self, machine, key):
        _write(machine / "license.json", _signed(key, expires_at="2020-01-01T00:00:00Z"))
        info = lumi_license.status()
        assert info["valid"] and info["expired"] and info["offline_use"] == "unlicensed"
        assert "expired 2020-01-01" in lumi_license.describe(info)
        lumi_license.reset_for_tests()
        _write(machine / "license.json", _signed(key, offline=False))
        info = lumi_license.status()
        assert info["valid"] and info["offline_use"] == "unlicensed"
        assert lumi_license.describe(info).endswith("Offline use isn't covered by this license.")

    @pytest.mark.parametrize("changes, fix", [
        ({"seats": 0}, "at least 1"), ({"seats": True}, "whole number"), ({"organization": " "}, "organization"),
        ({"expires_at": ""}, "expires"), ({"expires_at": "soon"}, "ISO 8601"), ({"offline": "yes"}, "true or false"),
        ({"schema": "lumi.license/v9"}, "schema"),
    ])
    def test_documents_lumi_cant_use(self, machine, key, changes, fix):
        with pytest.raises(LicenseError, match=fix):
            lumi_license.parse(_signed(key, **changes), trusted_keys=lumi_license.trusted_keys())

    def test_unsigned_licenses_are_refused(self, machine, key):
        with pytest.raises(LicenseError, match="must be signed"):
            lumi_license.parse(_signed(key)["license"], trusted_keys=lumi_license.trusted_keys())


class TestWhereLicensesLive:
    def test_no_license_is_fine(self, machine):
        info = lumi_license.status()
        assert info == {"present": False, "valid": False, "error": "", "source": "", "offline_use": "unlicensed",
                        "keys": 0}
        assert "work without one" in lumi_license.describe(info)

    def test_machine_file_wins_then_the_variable_then_the_installed_copy(self, machine, key, tmp_path, monkeypatch):
        from lumi.paths import state_home

        state_home().mkdir(parents=True, exist_ok=True)
        _write(state_home() / "license.json", _signed(key, organization="Installed"))
        assert lumi_license.load(force=True).license.organization == "Installed"
        variable = _write(tmp_path / "from-variable.json", _signed(key, organization="Variable"))
        monkeypatch.setenv("LUMI_LICENSE_FILE", str(variable))
        assert lumi_license.load(force=True).license.organization == "Variable"
        _write(machine / "license.json", _signed(key, organization="Machine"))
        assert lumi_license.load(force=True).license.organization == "Machine"

    def test_install_checks_then_keeps_a_copy(self, machine, key, tmp_path):
        from lumi.paths import state_home

        good = _write(tmp_path / "acme.json", _signed(key))
        lumi_license.install(good)
        assert (state_home() / "license.json").read_bytes() == good.read_bytes()
        assert lumi_license.status()["valid"]
        bad = _write(tmp_path / "bad.json", {**_signed(key), "signature": _signed(key, seats=1)["signature"]})
        with pytest.raises(LicenseError):
            lumi_license.install(bad)
        assert (state_home() / "license.json").read_bytes() == good.read_bytes()

    def test_the_command_line(self, machine, key, tmp_path, capsys):
        good = _write(tmp_path / "acme.json", _signed(key))
        assert lumi_license.main(["status"]) == 0
        assert "No license is installed" in capsys.readouterr().out
        assert lumi_license.main(["verify", str(good)]) == 0
        assert "Licensed to Acme" in capsys.readouterr().out
        assert lumi_license.main(["install", str(good)]) == 0
        assert capsys.readouterr().out.startswith("Installed. Licensed to Acme")
        assert lumi_license.main(["status", "--json"]) == 0
        assert json.loads(capsys.readouterr().out)["organization"] == "Acme"
        tampered = _write(tmp_path / "t.json", {**_signed(key), "key_id": "other"})
        assert lumi_license.main(["verify", str(tampered)]) == 1
        assert "doesn't trust" in capsys.readouterr().err


def _script():
    spec = importlib.util.spec_from_file_location("sign_license", ROOT / "scripts" / "sign_license.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestSigningScript:
    def test_keygen_sign_and_lumi_verifies(self, machine, tmp_path, capsys):
        script = _script()
        private = tmp_path / "luminary-license.pem"
        assert script.main(["keygen", "--out", str(private), "--key-id", "luminary-2026"]) == 0
        entry = json.loads(capsys.readouterr().out)
        if os.name != "nt":
            assert stat.S_IMODE(private.stat().st_mode) == 0o600
        with pytest.raises(SystemExit, match="refusing to overwrite"):
            script.main(["keygen", "--out", str(private), "--key-id", "luminary-2026"])
        out = tmp_path / "acme.json"
        assert script.main(["sign", "--key", str(private), "--key-id", "luminary-2026", "--organization", "Acme",
                            "--seats", "25", "--expires", "2099-06-30", "--offline", "--out", str(out)]) == 0
        capsys.readouterr()
        (machine / "license-keys.json").write_text(json.dumps(entry), encoding="utf-8")
        granted = lumi_license.parse(json.loads(out.read_text(encoding="utf-8")),
                                     trusted_keys=lumi_license.trusted_keys())
        assert (granted.organization, granted.seats, granted.offline) == ("Acme", 25, True)
        assert granted.expires_at == "2099-06-30T23:59:59Z"
        assert script.main(["public-key", "--key", str(private), "--key-id", "luminary-2026"]) == 0
        assert json.loads(capsys.readouterr().out) == entry
        assert script.main(["verify", str(out), "--public-key", entry["luminary-2026"],
                            "--key-id", "luminary-2026"]) == 0
